// Code generated by tools/genapi from internal/api's routes; DO NOT EDIT.

package apiclient

import (
	"context"
	"net/url"
	"strconv"
	"strings"

	"github.com/ar4mirez/berth/internal/mcpsrv"
	"github.com/ar4mirez/berth/internal/ops"
)

var _ = strconv.Itoa
var _ = strings.Join
var _ mcpsrv.Changed
var _ ops.Orgs

// HostsList is GET /v1/hosts: This machine and every registered host: whether each is reachable, its container engine, and how many orgs it has.
func (c *Client) HostsList(ctx context.Context) (out ops.Hosts, err error) {
	return out, c.do(ctx, "GET", "/v1/hosts", nil, nil, &out)
}

// OrgsList is GET /v1/orgs: Every org, here and on registered hosts: whether it is up, its ports, whether it has a Claude token, and its Remote Control state.
func (c *Client) OrgsList(ctx context.Context) (out ops.Orgs, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs", nil, nil, &out)
}

// OrgAccounts is GET /v1/accounts: Which Claude account and GitHub account each org is signed in to.
func (c *Client) OrgAccounts(ctx context.Context, orgs []string) (out ops.Whoami, err error) {
	q := url.Values{}
	if len(orgs) > 0 {
		q.Set("orgs", strings.Join(orgs, ","))
	}
	return out, c.do(ctx, "GET", "/v1/accounts", q, nil, &out)
}

// BackupsList is GET /v1/backups: The backup files on this machine, newest first: org, when, size and how each is encrypted.
func (c *Client) BackupsList(ctx context.Context, org string) (out ops.Backups, err error) {
	q := url.Values{}
	if org != "" {
		q.Set("org", org)
	}
	return out, c.do(ctx, "GET", "/v1/backups", q, nil, &out)
}

// BackupCreate is POST /v1/backups: Take an encrypted backup of orgs on this machine, into the backups directory.
func (c *Client) BackupCreate(ctx context.Context, orgs []string, all bool) (out mcpsrv.BackupsMade, err error) {
	return out, c.do(ctx, "POST", "/v1/backups", nil, map[string]any{"orgs": orgs, "all": all}, &out)
}

// ScheduleStatus is GET /v1/schedule: The nightly backup schedule on this machine: a systemd timer and its last runs, or a crontab line.
func (c *Client) ScheduleStatus(ctx context.Context) (out ops.Schedule, err error) {
	return out, c.do(ctx, "GET", "/v1/schedule", nil, nil, &out)
}

// OrgInfo is GET /v1/orgs/{org}: An org's connection sheet: its state, address and ports, the claude.ai/code link, and its git public key.
func (c *Client) OrgInfo(ctx context.Context, org string) (out ops.Info, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org), nil, nil, &out)
}

// RemoteStatus is GET /v1/orgs/{org}/remote: Remote Control in a running org: on, login-needed, blocked-by-org or restarting, with its link and capacity when on.
func (c *Client) RemoteStatus(ctx context.Context, org string) (out ops.RemoteStatus, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/remote", nil, nil, &out)
}

// OrgLogs is GET /v1/orgs/{org}/logs: The last lines of a running org's container log (startup, firewall, Remote Control).
func (c *Client) OrgLogs(ctx context.Context, org string, lines int) (out ops.Logs, err error) {
	q := url.Values{}
	if lines != 0 {
		q.Set("lines", strconv.Itoa(lines))
	}
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/logs", q, nil, &out)
}

// FirewallShow is GET /v1/orgs/{org}/firewall: An org's egress allowlist as written, and the live firewall status of its container.
func (c *Client) FirewallShow(ctx context.Context, org string) (out ops.Firewall, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/firewall", nil, nil, &out)
}

// FirewallPresets is GET /v1/orgs/{org}/firewall/presets: The firewall's @presets and the hosts each one allows.
func (c *Client) FirewallPresets(ctx context.Context, org string) (out ops.Presets, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/firewall/presets", nil, nil, &out)
}

// FirewallTest is POST /v1/orgs/{org}/firewall/test: Whether a running org can reach each host or URL now, tried from inside its container.
func (c *Client) FirewallTest(ctx context.Context, org string, hosts []string) (out ops.FirewallTest, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/firewall/test", nil, map[string]any{"hosts": hosts}, &out)
}

// FirewallAllow is POST /v1/orgs/{org}/firewall/allow: Add entries to an org's egress allowlist.
func (c *Client) FirewallAllow(ctx context.Context, org string, entries []string) (out mcpsrv.FirewallChanged, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/firewall/allow", nil, map[string]any{"entries": entries}, &out)
}

// FirewallDeny is POST /v1/orgs/{org}/firewall/deny: Remove entries from an org's egress allowlist, exactly as written there.
func (c *Client) FirewallDeny(ctx context.Context, org string, entries []string) (out mcpsrv.FirewallChanged, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/firewall/deny", nil, map[string]any{"entries": entries}, &out)
}

// ReposList is GET /v1/orgs/{org}/repos: An org's registered repos, with branch and uncommitted changes when its container reports them, and anything in its workspace that isn't registered.
func (c *Client) ReposList(ctx context.Context, org string) (out ops.Repos, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/repos", nil, nil, &out)
}

// RepoAdd is POST /v1/orgs/{org}/repos: Register a repository for an org and clone it into /workspace.
func (c *Client) RepoAdd(ctx context.Context, org string, repo string, dir string, branch string, noClone bool) (out mcpsrv.Changed, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/repos", nil, map[string]any{"repo": repo, "dir": dir, "branch": branch, "no_clone": noClone}, &out)
}

// RepoRemove is DELETE /v1/orgs/{org}/repos/{dir}: Unregister a repo from an org.
func (c *Client) RepoRemove(ctx context.Context, org string, dir string) (out mcpsrv.Changed, err error) {
	return out, c.do(ctx, "DELETE", "/v1/orgs/"+url.PathEscape(org)+"/repos/"+url.PathEscape(dir), nil, nil, &out)
}

// EnvList is GET /v1/orgs/{org}/env: The names of an org's custom environment variables.
func (c *Client) EnvList(ctx context.Context, org string) (out ops.Env, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/env", nil, nil, &out)
}

// PackagesList is GET /v1/orgs/{org}/packages: The system packages an org's image adds, and that image.
func (c *Client) PackagesList(ctx context.Context, org string) (out ops.Packages, err error) {
	return out, c.do(ctx, "GET", "/v1/orgs/"+url.PathEscape(org)+"/packages", nil, nil, &out)
}

// OrgUp is POST /v1/orgs/{org}/up: Start an org: gets its image if needed, then recreates its container.
func (c *Client) OrgUp(ctx context.Context, org string, confirm string) (out mcpsrv.Changed, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/up", nil, map[string]any{"confirm": confirm}, &out)
}

// OrgRestart is POST /v1/orgs/{org}/restart: Restart an org: recreates its container, applying pending changes (a new image, packages, variables).
func (c *Client) OrgRestart(ctx context.Context, org string, confirm string) (out mcpsrv.Changed, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/restart", nil, map[string]any{"confirm": confirm}, &out)
}

// OrgDown is POST /v1/orgs/{org}/down: Stop an org: stops and removes its container.
func (c *Client) OrgDown(ctx context.Context, org string, confirm string) (out mcpsrv.Changed, err error) {
	return out, c.do(ctx, "POST", "/v1/orgs/"+url.PathEscape(org)+"/down", nil, map[string]any{"confirm": confirm}, &out)
}
