// genapi writes the Go client's methods (internal/apiclient/client_gen.go) from the API's route
// table, one per endpoint: go run ./tools/genapi.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"

	"github.com/ar4mirez/berth/internal/api"
)

func camel(s string, first bool) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if (i > 0 || first) && p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func goType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Slice:
		return "[]string"
	case reflect.Int:
		return "int"
	case reflect.Bool:
		return "bool"
	}
	return "string"
}

// Source is the generated file.
func Source() ([]byte, error) {
	specs := api.Specs()
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genapi from internal/api's routes; DO NOT EDIT.\n\npackage apiclient\n\n")
	b.WriteString("import (\n\t\"context\"\n\t\"net/url\"\n\t\"strconv\"\n\t\"strings\"\n\n\t\"github.com/ar4mirez/berth/internal/mcpsrv\"\n\t\"github.com/ar4mirez/berth/internal/ops\"\n)\n\n")
	b.WriteString("var _ = strconv.Itoa\nvar _ = strings.Join\nvar _ mcpsrv.Changed\nvar _ ops.Orgs\n\n")
	for _, r := range api.Routes {
		spec := specs[r.Tool]
		args := r.Args(spec.In)
		var params []string
		path := `"` + r.Path + `"`
		var query, body []string
		for _, a := range args {
			name := camel(a.Name, false)
			params = append(params, name+" "+goType(a.Type))
			switch a.In {
			case "path":
				path = strings.Replace(path, "{"+a.Name+"}", `" + url.PathEscape(`+name+`) + "`, 1)
			case "query":
				switch a.Type.Kind() {
				case reflect.Slice:
					query = append(query, fmt.Sprintf("if len(%[1]s) > 0 {\n\t\tq.Set(%[2]q, strings.Join(%[1]s, \",\"))\n\t}", name, a.Name))
				case reflect.Int:
					query = append(query, fmt.Sprintf("if %[1]s != 0 {\n\t\tq.Set(%[2]q, strconv.Itoa(%[1]s))\n\t}", name, a.Name))
				default:
					query = append(query, fmt.Sprintf("if %[1]s != \"\" {\n\t\tq.Set(%[2]q, %[1]s)\n\t}", name, a.Name))
				}
			default:
				body = append(body, fmt.Sprintf("%q: %s", a.Name, name))
			}
		}
		path = strings.TrimSuffix(path, ` + ""`)
		summary, _, _ := strings.Cut(spec.Description, ". ")
		fmt.Fprintf(&b, "// %s is %s %s: %s.\n", camel(r.Tool, true), r.Method, r.Path, strings.TrimSuffix(summary, "."))
		fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context%s) (out %s, err error) {\n", camel(r.Tool, true), prefix(params), spec.Out.String())
		q := "nil"
		if len(query) > 0 {
			q = "q"
			b.WriteString("\tq := url.Values{}\n\t" + strings.Join(query, "\n\t") + "\n")
		}
		bd := "nil"
		if len(body) > 0 {
			bd = "map[string]any{" + strings.Join(body, ", ") + "}"
		}
		fmt.Fprintf(&b, "\treturn out, c.do(ctx, %q, %s, %s, %s, &out)\n}\n\n", r.Method, path, q, bd)
	}
	return format.Source(b.Bytes())
}

func prefix(params []string) string {
	if len(params) == 0 {
		return ""
	}
	return ", " + strings.Join(params, ", ")
}

func main() {
	src, err := Source()
	if err == nil {
		err = os.WriteFile("internal/apiclient/client_gen.go", src, 0o644) //nolint:gosec // a source file
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "genapi:", err)
		os.Exit(1)
	}
}
