// Package docgen generates berth's command reference (Markdown, for the docs site) and its man
// pages from the cobra tree, so they're always current (#56). tools/gendocs writes them;
// internal/cli's TestCommandReferenceIsCurrent fails when docs/reference/commands is stale.
package docgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// Site is the docs site (GitHub Pages, built from docs/ by .github/workflows/docs.yml).
const Site = "https://ar4mirez.github.io/berth"

// RefDir is the command reference, under docs/.
const RefDir = "reference/commands"

// base is a command's page name: "berth org up" -> berth_org_up.
func base(path string) string { return strings.ReplaceAll(path, " ", "_") }

// PageURL is the docs page of a command path ("berth up").
func PageURL(path string) string { return Site + "/" + RefDir + "/" + base(path) + "/" }

func noAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true // no generation date: the pages must be reproducible
	for _, s := range c.Commands() {
		noAutoGenTag(s)
	}
}

// Markdown writes one page per command (hidden ones excluded) into dir.
func Markdown(root *cobra.Command, dir string) error {
	noAutoGenTag(root)
	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:forbidigo,gosec // the repo's docs (world-readable), not org state
		return err
	}
	front := func(file string) string {
		name := strings.TrimSuffix(filepath.Base(file), ".md")
		return fmt.Sprintf("---\ntitle: %s\n---\n\n<!-- Generated by tools/gendocs from the commands' help. Don't edit. -->\n\n", strings.ReplaceAll(name, "_", " "))
	}
	return doc.GenMarkdownTreeCustom(root, dir, front, func(s string) string { return s })
}

// Man writes man pages (section 1), one per command, into dir.
func Man(root *cobra.Command, dir, version string) error {
	noAutoGenTag(root)
	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:forbidigo,gosec // the repo's docs (world-readable), not org state
		return err
	}
	return doc.GenManTree(root, &doc.GenManHeader{Title: "BERTH", Section: "1", Source: "berth " + version, Manual: "berth manual"}, dir)
}

// Completions writes the shell completion scripts packages install: berth.bash, _berth (zsh) and
// berth.fish.
func Completions(root *cobra.Command, dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:forbidigo,gosec // release files (world-readable), not org state
		return err
	}
	for name, gen := range map[string]func(*os.File) error{
		"berth.bash": func(f *os.File) error { return root.GenBashCompletionV2(f, true) },
		"_berth":     func(f *os.File) error { return root.GenZshCompletion(f) },
		"berth.fish": func(f *os.File) error { return root.GenFishCompletion(f, true) },
	} {
		f, err := os.Create(filepath.Join(dir, name)) //nolint:forbidigo,gosec // as above
		if err != nil {
			return err
		}
		if err := gen(f); err != nil {
			_ = f.Close()
			return err
		}
		if err := f.Close(); err != nil {
			return err
		}
	}
	return nil
}
