package ops

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"path"
	"regexp"
	"sort"
	"strings"
)

// Per-org system packages (#106). An org's config/packages.txt lists Debian packages its projects
// need and berth's image doesn't have (a browser's libraries, say). berth builds a thin image for
// that org on top of its own, with them installed, and runs the org on it. The packages are
// installed at build time, so the org's firewall needs no Debian mirror, and they survive every
// recreate of the container.

// PackagesFile is an org's packages.txt.
func PackagesFile(s System, org string) string {
	return path.Join(s.OrgsDir(), org, "config", "packages.txt")
}

// PackagesHeader starts a new packages.txt.
func PackagesHeader(org string) string {
	return Respell("# System packages installed in " + org + "'s image, managed with: " + Tool + " pkg " + org + " add|rm ...\n" +
		"# One Debian package or @preset per line. Presets: " + Tool + " pkg " + org + " presets\n")
}

// PackagePresets are named sets of packages.
var PackagePresets = map[string][]string{
	// What Playwright's Chromium needs on Debian 12 to launch headless and render text as CI does:
	// `playwright install-deps chromium`'s list, without xvfb and xfonts-scalable (headed runs only).
	"@playwright-chromium": strings.Fields(`libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3
		libdrm2 libgbm1 libglib2.0-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6
		libxfixes3 libxkbcommon0 libxrandr2 libfontconfig1 libfreetype6
		fonts-liberation fonts-noto-color-emoji fonts-freefont-ttf fonts-unifont fonts-ipafont-gothic fonts-wqy-zenhei
		fonts-tlwg-loma-otf`),
}

// PresetNames are the presets, sorted.
func PresetNames() []string {
	var names []string
	for n := range PackagePresets {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// debPackage is a Debian binary package name (Policy 5.6.1): nothing else reaches apt's command line.
var debPackage = regexp.MustCompile(`^[a-z0-9][a-z0-9+.-]+$`)

// CheckPackage refuses an entry that is neither a Debian package name nor a known preset.
func CheckPackage(e string) error {
	switch {
	case strings.HasPrefix(e, "@"):
		if _, ok := PackagePresets[e]; !ok {
			return fail(KindUsage, "presets: "+strings.Join(PresetNames(), " "), "unknown preset '%s'", e)
		}
	case !debPackage.MatchString(e):
		return fail(KindUsage, "", "'%s' isn't a Debian package name (lowercase letters, digits, + . -) or an @preset", e)
	}
	return nil
}

// PackageEntries are packages.txt's entries, as written: one per line, `#` comments and blank lines
// left out. A missing file has none.
func PackageEntries(s System, org string) []string {
	b, err := s.ReadFile(PackagesFile(s, org))
	if err != nil {
		return nil
	}
	var out []string
	for _, l := range lines(b) {
		if l, _, _ = strings.Cut(l, "#"); strings.TrimSpace(l) != "" {
			out = append(out, strings.Fields(l)...)
		}
	}
	return out
}

// ExpandPackages is the packages the entries stand for: presets expanded, duplicates dropped,
// sorted. An entry that isn't valid (a hand-edited file) is left out and returned in bad.
func ExpandPackages(entries []string) (pkgs, bad []string) {
	seen := map[string]bool{}
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			pkgs = append(pkgs, p)
		}
	}
	for _, e := range entries {
		switch {
		case CheckPackage(e) != nil:
			bad = append(bad, e)
		case strings.HasPrefix(e, "@"):
			for _, p := range PackagePresets[e] {
				add(p)
			}
		default:
			add(e)
		}
	}
	sort.Strings(pkgs)
	return pkgs, bad
}

// OrgImage is the image an org with these packages runs on: berth/claude-env-<org>:<base>-<list>,
// where base is the base image's own hash and list a hash of the package list, so a change to
// either is a new image. With no packages it is the base image.
func OrgImage(base, org string, pkgs []string) string {
	if len(pkgs) == 0 {
		return base
	}
	repo, tag, _ := strings.Cut(base, ":")
	sum := sha256.Sum256([]byte(strings.Join(pkgs, "\n")))
	return repo + "-" + org + ":" + tag + "-" + hex.EncodeToString(sum[:])[:12]
}

// OrgDockerfile is the build of an org's image: the base, plus its packages.
func OrgDockerfile(base, org string, pkgs []string) string {
	return "# Generated by " + Tool + " for " + org + ", from its config/packages.txt (" + Tool + " pkg " + org + "). Don't edit: it is rewritten.\n" +
		"FROM " + base + "\n" +
		"# compose passes these to every build; the base image has already used them.\n" +
		"ARG USER_UID\nARG USER_GID\n" +
		"USER root\n" +
		"RUN apt-get update \\\n" +
		" && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n" +
		"      " + strings.Join(pkgs, " ") + " \\\n" +
		" && rm -rf /var/lib/apt/lists/*\n" +
		"LABEL berth.org=\"" + org + "\"\n"
}

// GetPackages is `pkg <org>`: the org's entries, the packages they stand for, and its image.
func GetPackages(ctx context.Context, s System, org string) (Packages, error) {
	out := Packages{Schema: "berth.packages/v1", Org: org, File: PackagesFile(s, org), Entries: []string{}, Packages: []string{}, Invalid: []string{}}
	if err := NeedOrg(s, org); err != nil {
		return out, err
	}
	out.Entries = append(out.Entries, PackageEntries(s, org)...)
	pkgs, bad := ExpandPackages(out.Entries)
	out.Packages = append(out.Packages, pkgs...)
	out.Invalid = append(out.Invalid, bad...)
	base, err := s.Image()
	if err != nil {
		return out, err
	}
	out.BaseImage = base
	out.Image = OrgImage(base, org, pkgs)
	out.Built = s.Silent(ctx, "docker", "image", "inspect", out.Image)
	return out, nil
}

// GetPackagePresets is `pkg <org> presets`.
func GetPackagePresets() PackagePresetsDoc {
	out := PackagePresetsDoc{Schema: "berth.package-presets/v1", Presets: []PackagePreset{}}
	for _, n := range PresetNames() {
		out.Presets = append(out.Presets, PackagePreset{Name: n, Packages: PackagePresets[n]})
	}
	return out
}
